# The vendored macOS engine (README's setup step) is the default, not the rule:
# CI fetches the Linux build of the same version and points GODOT at it, by
# path or by a name on PATH — require-godot below and every gate script accept
# both, through the one test in tools/lib/require_godot.sh.
GODOT ?= bin/Godot.app/Contents/MacOS/Godot
# Windowed launches go through a wrapper that hands window focus straight back
# when the launch came from a script or an agent (no tty); from an interactive
# terminal it execs $(GODOT) directly. See tools/godot_gui.sh for why the
# steal can't be prevented outright.
GODOT_GUI := GODOT="$(GODOT)" tools/godot_gui.sh
BATTLE := scenes/battle/battle.tscn
# The unit and terrain atlases are generated by generators/sprites
# (deterministic voxel pipeline, no third-party art); the committed atlases are
# its output, so a clone that never runs it still plays.
SPRITEGEN ?= generators/sprites
# Where make export-android drops the debug package. Ignored by git.
ANDROID_APK ?= build/android/grid_commanders.apk
# Where make export-ios drops the Xcode project. The .ipa path is what the
# preset names; with export_project_only the project lands beside it instead.
# Ignored by git, like the APK.
IOS_IPA ?= build/ios/grid_commanders.ipa
IOS_XCODEPROJ ?= build/ios/grid_commanders.xcodeproj
IOS_EXPORT_OPTIONS ?= build/ios/grid_commanders/export_options.plist
# The placeholder team id committed in export_presets.cfg. Rewriting the
# placeholder itself is what covers every place the generated project repeats
# it: DEVELOPMENT_TEAM in both build configurations, the target's
# DevelopmentTeam attribute, and teamID in export_options.plist.
IOS_TEAM_PLACEHOLDER := AAAAAAAAAA

# The two things a gate can be missing. The gate scripts say the first for
# themselves, through tools/lib/require_godot.sh; a target that runs the tool
# directly says it here, in the same two lines, so a fresh machine reads the
# setup line instead of a bare "No such file or directory".
require-godot = @test -x "$(GODOT)" || command -v "$(GODOT)" >/dev/null || { \
	echo "$@: Godot binary not found at $(GODOT)" >&2; \
	echo "$@: see README.md for engine setup, or pass GODOT=<path>" >&2; \
	exit 1; }
require-gdtoolkit = @command -v $(1) >/dev/null || { \
	echo "$@: $(1) not found — pipx install \"gdtoolkit==4.*\"" >&2; \
	exit 1; }

run: import
	$(GODOT_GUI) --path .

hotseat: import
	$(GODOT_GUI) --path . $(BATTLE) -- --hotseat

# Two engines at once: the two soaks in one, every other script in the other.
# TEST_JOBS=1 runs the single verbatim .gutconfig.json pass. See tools/run_tests.sh.
test:
	$(call require-godot)
	GODOT="$(GODOT)" tools/run_tests.sh

# The merge gate, in one command. Order is cheapest-feedback-first: parsing
# fails fastest, style next, the suite last, then the ~1s determinism replay.
#
# Note on exit noise: every headless run ends with "N ObjectDB instances were
# leaked at exit" and "resources still in use". That is the engine failing to
# tear down a *script* reference cycle — AttackCommand.validate() referring to
# its sibling MoveCommand pins the core script graph — and it reproduces in
# a dozen lines with no GUT involved. No gameplay object leaks. Attempted
# workarounds (static call, split statements) do not avoid it, so the gate
# reads exit status and ignores the diagnostics.
#
# Needs Godot 4.7+ (vendored under bin/, see README) and gdtoolkit 4.x for the
# lint and format steps: pipx install "gdtoolkit==4.*"
verify: check lint format-check test determinism

# Presentation smoke: drives the battle scene's demo scenarios and proves each
# still produces a frame. Renders, so it needs a display — keep it out of any
# headless CI job. `make smoke MODES="attack capture"` narrows it down;
# a `+fog` suffix reruns a scenario with fog of war on (`victory+fog`), which is
# the only setting where sprites are hidden rather than merely drawn;
# SMOKE_KEEP=1 keeps the captures for eyeballing, and SMOKE_ISOLATE=1 turns off
# the one-boot batching (one process per scenario; see README).
# A `menu_` mode boots the main
# menu instead of the board and gates it against the 640x360 frame (COM-5); the
# set and what each one proves is in the README.
# Imports first the way run and screenshot do: a stale class cache leaves the
# sweep booting scenarios that never draw, which reads as a long hang rather than
# as a cold tree.
MODES ?=
smoke: import
	tools/smoke_scenarios.sh $(MODES)

# Offline commander balance: plays AI-vs-AI across every pairing on five
# rotationally-symmetric scenarios and writes a per-match CSV + a JSON summary to
# reports/ (gitignored). The full batch (no args) is a long headless release task,
# deliberately out of `make verify` and `make test` — docs/commander_balance.md has
# its exact size and every flag. Narrow it for iteration, e.g.:
#   make commander-balance BAL="--commanders=alina_ward,cass_orlov --seeds=2"
# The committed artifacts of a balance pass are tuned data/commanders/*.tres and
# docs/commander_balance.md, never the generated report.
BAL ?=
commander-balance:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_commander_balance.gd -- $(BAL)

# The difficulty ladder gate (plan DF4): the same runner in --difficulty-check
# mode, playing Easy-vs-Normal and Normal-vs-Difficult on two mirrored maps with
# both sides swapped. Unlike commander balance this one *is* a gate — with no
# economy or damage handicap at any tier, the higher tier's win rate is the only
# evidence that "smarter, not cheating" is true, so a shortfall fails the run.
# It fails today, knowingly — read docs/difficulty_check.md's standing verdict
# before treating a red run as a regression. Narrow it for iteration, e.g.:
#   make difficulty-check DIFF="--seeds=2 --days=15"
# The committed artifacts of a tuning pass are the profiles under data/ai/ and
# docs/difficulty_check.md, never the generated report.
DIFF ?=
difficulty-check:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_commander_balance.gd -- \
		--difficulty-check $(DIFF)

# The Bulwark fairness measurement (asymmetric-board plan AB3): the win spread
# over N seeds, AI on all four seats, neutral commanders. BalanceMatchEngine
# plays two sides and this board plays four, so it is its own runner rather
# than a third preset over that engine — see tools/run_bulwark_measure.gd.
# A measurement, not a gate: out of `make verify` and `make test`, and it tunes
# nothing — docs/bulwark_balance.md is the committed record, never the
# generated report. Narrow it for iteration, e.g.:
#   make bulwark-measure BULWARK="--seeds=4 --days=40"
BULWARK ?=
bulwark-measure:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_bulwark_measure.gd -- $(BULWARK)

# The same instrument pointed at any four-army board and any tier — the win
# spread, and how long a match takes to get there (mean_day / median_day /
# decided_pct), which the two-sided balance reports cannot read at all. Name the
# board's grouping in the `--sides=` grammar, or `ffa` for the free-for-all
# every four-seat board's seat strip offers. A measurement, not a gate, exactly
# as bulwark-measure is. Examples:
#   make board-measure BOARD="--map=causeway --grouping=ffa --seeds=20"
#   make board-measure BOARD="--map=compass --grouping=1+3v2+4 --tier=hard"
BOARD ?=
board-measure:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_bulwark_measure.gd -- $(BOARD)

# The Balance Lab: the general instrument the two presets above are special
# cases of. Any shipped map, any commander at any tier per side, N seeded
# matches with both seats swapped, and a turn-by-turn timeline of how each one
# went. Like its two siblings it is an opt-in instrument, not a merge gate, so
# it stays out of `make verify` and `make test`; only its own unit tests
# (recorder attribution, engine determinism) are in the suite.
# docs/balance_sim.md has every flag and how to read the output. Examples:
#   make balance-sim SIM="--map=ironworks --red=gideon_holt:normal --blue=cass_orlov:normal --seeds=10"
#   make balance-sim SIM="--sweep=maps --seeds=6"
SIM ?=
balance-sim:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_balance_sim.gd -- $(SIM)

# The same Lab, sharded across processes: one headless engine per shard, several
# at a time, and resumable — a shard whose summary.json exists is skipped, so a
# killed sweep costs the shard in flight and nothing else. The merged matches.csv
# is what the same spec written as one `balance-sim` run produces, byte for byte.
# Not a gate; it is how a long sweep is played:
#   make balance-pool POOL="--maps=ironworks --pairings=none:normal/none:hard --seeds=32"
# docs/balance_sim.md has the flags, the merge bar and the measured scaling curve.
# The pool drives either preset over that engine: `--preset=arena` plays the
# shards with tools/run_ai_arena.gd instead, whose sides are profile paths and
# whose shards merge as JSON.
POOL ?=
balance-pool:
	GODOT="$(GODOT)" tools/balance_pool.py $(POOL)

# The AI Arena's match driver (arena plan AR3): the same one match loop as the
# Lab, given the one input the Lab's <commander>:<tier> grammar cannot state —
# "play *this* AIProfile". Writes one JSON record per match and nothing else, so
# a tournament's telemetry cost is a record rather than a timeline; a pairing
# worth a closer look is re-run through `make balance-sim` with the full
# instruments on. An instrument, not a gate:
#   make ai-arena ARENA="--red-profile=data/ai/default.tres --blue-profile=data/ai/hard.tres --seeds=8"
#   make ai-arena ARENA="--pairings=reports/ai_arena/gen1/shard0.json"
# A whole matrix goes through the pool: make balance-pool POOL="--preset=arena …"
ARENA ?=
ai-arena:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_ai_arena.gd -- $(ARENA)

# Score a finished arena run: one row per candidate, in each pool (arena plan
# AR4). Reads records and plays nothing, so re-scoring a run after the fitness
# function moves costs no matches. docs/ai_arena.md is the function it applies.
#   make arena-report REPORT="--matches=reports/ai_arena/anchors_training"
REPORT ?=
arena-report:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_arena_report.gd -- $(REPORT)

# The calibration, end to end: play one fixed pool of the anchor round-robin
# across the cores and score it. `ARENA_POOL=training` or `ARENA_POOL=validation`
# — its own knob rather than `POOL`, which balance-pool already defines as the
# empty flag list; the two share no default. The boards, seeds and pairings are
# ArenaPools' and are read out of it rather than spelled here, so the command
# that plays a pool cannot drift from the split the report reads matches back
# against. The engine prints a banner before the argument line, which is what
# the grep is for.
ARENA_POOL ?= training
WORKERS ?= 6
arena-anchors:
	$(call require-godot)
	@plan=$$($(GODOT) --headless --path . -s res://tools/run_arena_plan.gd -- \
		--pool=$(ARENA_POOL) | grep '^--maps=') && \
	echo "arena: $(ARENA_POOL) pool -> $$plan" && \
	GODOT="$(GODOT)" tools/balance_pool.py --preset=arena $$plan \
		--batch=4 --workers=$(WORKERS) --out=ai_arena/anchors_$(ARENA_POOL) && \
	$(GODOT) --headless --path . -s res://tools/run_arena_report.gd -- \
		--matches=reports/ai_arena/anchors_$(ARENA_POOL)

# Search a block of planner dials against the fixed anchors (arena plan AR5).
# The loop over the three instruments above — propose a vector, play it through
# the pool, score it through the report — and nothing else: it edits no data/
# file, and every candidate it writes stays under reports/ so a champion can be
# re-run and explained afterwards. Blocks, never one joint optimisation (R5);
# `tools/arena/arena_blocks.gd` is which dials are in which and why.
# State the cost before spending it:
#   make arena-search SEARCH="--block=all --dry-run"
#   make arena-search SEARCH="--block=combat --train-seeds=6"
# Rerun the same command to resume one; docs/ai_arena.md has the algorithm.
SEARCH ?=
arena-search:
	GODOT="$(GODOT)" tools/arena_search.py $(SEARCH)

# Watch a match from a report play out in the real game window, both sides AI.
# Same spec grammar and the same seed, so a suspicious row in matches.csv
# becomes the exact battle it describes:
#   make balance-watch SIM="--map=ironworks --red=gideon_holt:normal --blue=cass_orlov:normal --seed=1003"
# Windowed, so it goes through the focus-safe wrapper like every other GUI target.
balance-watch: import
	$(GODOT_GUI) --path . $(BATTLE) -- --watch $(SIM)

# Watch a recorded match. Every match records itself to a rotating slot under
# user://replays/ as it is played, and `make balance-sim SIM="... --replays"`
# writes one per headless match beside its report:
#   make replay REPLAY=~/Library/Application\ Support/Godot/app_userdata/Grid\ Commanders/replays/<file>.jsonl
# Unlike `balance-watch`, which re-plans a row from its seed, this re-issues the
# commands that were actually played — so it is immune to AI changes by design,
# and stops out loud when a rules or data edit means the board no longer matches.
REPLAY ?=
replay: import
	$(GODOT_GUI) --path . $(BATTLE) -- --replay="$(REPLAY)"

# Read a recording instead of watching it: re-issue every command offline and
# report what the sides left on the table — a unit that stood still, funds never
# spent, a Command Power banked to the end, a tank walked into three guns.
#   make replay-report REPLAY=<file> [ARGS="--team=2"]
#   make replay-report REPLAY=<dir>   # surveys every .jsonl in it: survey.md + survey.json
# Every counterfactual comes from the rules, never from the planner, so a finding
# is about the game rather than about one revision of ai/. It is evidence and not
# a gate — several detectors fire on a doctrine playing exactly as intended — so
# it stays out of `make verify`. Writes to reports/ (gitignored).
ARGS ?=
replay-report:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_replay_report.gd -- \
		--replay="$(REPLAY)" $(ARGS)

# Composite legibility: renders every unit kind, in every faction's colours,
# ready and acted, over grass, woods, sea, mountain and shoal, under the move,
# fire, threat and fog layers, and reports how many ramp steps of separation the
# figure's own contour keeps from the ground just outside it — plus, beside it,
# the CIE76 chroma distance over the same pairs, so a shape told apart by hue
# alone is counted rather than passed, and the whole-figure medians behind both
# as a secondary. Reads the shipped atlases and the shipped constants and plays
# no match.
# It boots a bare scene rather than running with -s, because the board constants
# it reads sit on scripts that name autoloads.
#   make legibility-check
#   make legibility-check LEGIBILITY="--worst=40 \
#     --dump=board:idle_a:tank:verdant:ready:woods:atlas:none"
# An instrument rather than a gate — a failing cell is a finding for the art to
# answer, never a colour to move — so it stays out of `make verify`, like the
# Balance Lab. docs/sprite_legibility.md is the committed reading; the run
# writes its tables to reports/ (gitignored) and redraws the one committed
# artifact it publishes, docs/images/legibility_worst20.png.
LEGIBILITY ?=
legibility-check:
	$(call require-godot)
	$(GODOT) --headless --path . res://tools/run_legibility_check.tscn -- $(LEGIBILITY)

# Every .gd file that is actually ours: skips the engine cache, vendored addons,
# the engine binary, and .claude/worktrees, which holds whole nested checkouts of
# this same repo and would otherwise be linted as if it were project source.
#
# Deferred, so only the three gdtoolkit targets below pay for the walk — `:=`
# ran it on every invocation, `make run` included.
SOURCES = $(shell find . -name '*.gd' \
	-not -path './.godot/*' -not -path './addons/*' -not -path './bin/*' \
	-not -path './.claude/*')

# Parse/type check plus lightweight architecture invariants without booting the
# scene tree. Rules live in tools/check_scripts.sh.
check:
	tools/check_scripts.sh

# The determinism gate (balance plan D1): one pinned Balance Lab match, byte-
# diffed against the golden report under tests/fixtures/determinism/. About a
# second, so unlike its two full-size siblings it runs on every change and in CI.
# A deliberate rules, data or planner change is supposed to move it:
#   make determinism REFRESH=1   rewrite the golden after reading the diff
REFRESH ?=
determinism:
	tools/check_determinism.sh $(if $(REFRESH),--refresh)

# Style and smells. Rule overrides live in gdlintrc.
lint:
	$(call require-gdtoolkit,gdlint)
	gdlint $(SOURCES)

# Reformat in place; `make format-check` only reports. Both need gdtoolkit:
#   pipx install "gdtoolkit==4.*"
format:
	$(call require-gdtoolkit,gdformat)
	gdformat $(SOURCES)

format-check:
	$(call require-gdtoolkit,gdformat)
	gdformat --check $(SOURCES)

# `atlases` regenerates both sheets with generators/sprites and installs them
# (plus the per-cell reference sprites) here; `ui-art` draws the overlay, cursor
# and icon, the art that pipeline has no home for.
# `import` runs last because Godot caches image imports by size: without it a
# rebuild that changes the atlas dimensions renders a blank map.
# .NOTPARALLEL keeps that order under `make -j`, and it is file-scope on
# purpose: `verify`'s four gates are a sequence rather than a set — they share
# one .godot/ across every engine boot, and their order is the cheapest
# feedback first, so racing them would trade a one-second parse failure for
# the suite's ninety. Scoping it would be inert here anyway — prerequisites
# are honoured by GNU make 4.4 and up, and macOS ships 3.81, which serialises
# the whole file regardless.
.NOTPARALLEL:

tiles: atlases ui-art import

atlases:
	$(call require-spritegen)
	"$(SPRITEGEN_PY)" "$(SPRITEGEN)/sprite_generator.py" \
		-o "$(SPRITEGEN)/out" --install "$(CURDIR)"

ui-art:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/generate_tiles.gd

# The sound effects and the two music loops are composed and gated in
# generators/audio (see assets/LICENSES.md) and installed here as committed
# WAVs and Oggs. The interpreter deliberately lives OUTSIDE the checkout: a git
# worktree shares no ignored files with the main checkout, so a venv under the
# tree is one reinstall per worktree. `make generators-venv` creates it.
AUDIOGEN ?= generators/audio
AUDIOGEN_VENV ?= $(HOME)/.cache/grid_commanders/venv-audio
AUDIOGEN_PY ?= $(AUDIOGEN_VENV)/bin/python

define require-audiogen
	@test -x "$(AUDIOGEN_PY)" || { \
		echo "$@: no interpreter at $(AUDIOGEN_PY) — run \`make generators-venv\`," >&2; \
		echo "$@: or pass AUDIOGEN_PY=<python with numpy and soundfile>" >&2; \
		exit 1; }
endef

# The board art is generated by generators/sprites (SPRITEGEN, above) and its
# interpreter lives outside the checkout for the same reason the audio one does.
SPRITEGEN_VENV ?= $(HOME)/.cache/grid_commanders/venv-sprites
SPRITEGEN_PY ?= $(SPRITEGEN_VENV)/bin/python

define require-spritegen
	@test -x "$(SPRITEGEN_PY)" || { \
		echo "$@: no interpreter at $(SPRITEGEN_PY) — run \`make generators-venv\`," >&2; \
		echo "$@: or pass SPRITEGEN_PY=<python with Pillow>" >&2; \
		exit 1; }
endef

# The commander art is generated by generators/portraits, on the same terms.
PORTRAITGEN ?= generators/portraits
PORTRAITGEN_VENV ?= $(HOME)/.cache/grid_commanders/venv-portraits
PORTRAITGEN_PY ?= $(PORTRAITGEN_VENV)/bin/python

define require-portraitgen
	@test -x "$(PORTRAITGEN_PY)" || { \
		echo "$@: no interpreter at $(PORTRAITGEN_PY) — run \`make generators-venv\`," >&2; \
		echo "$@: or pass PORTRAITGEN_PY=<python with Pillow>" >&2; \
		exit 1; }
endef

# Every pipeline's interpreter in one target: a contributor who needs one
# usually needs the others, and three targets to remember is three to forget.
generators-venv:
	python3 -m venv "$(AUDIOGEN_VENV)"
	"$(AUDIOGEN_PY)" -m pip install --quiet --requirement "$(AUDIOGEN)/requirements.txt"
	python3 -m venv "$(SPRITEGEN_VENV)"
	"$(SPRITEGEN_PY)" -m pip install --quiet --requirement "$(SPRITEGEN)/requirements.txt"
	python3 -m venv "$(PORTRAITGEN_VENV)"
	"$(PORTRAITGEN_PY)" -m pip install --quiet --requirement "$(PORTRAITGEN)/requirements.txt"

# `import` runs last for the reason `tiles` does: Godot caches by size, so a
# stale import plays the old sound — or silence.
audio:
	$(call require-audiogen)
	"$(AUDIOGEN_PY)" "$(AUDIOGEN)/audio_generator.py" \
		-o "$(AUDIOGEN)/out" --install "$(CURDIR)"
	$(MAKE) import

# The generator's own merge bar: rosters, determinism, mix levels, loop seams
# and pairwise distinctness. Out of `make verify` because it costs ~20 s and
# needs a Python venv a clone of this repo does not have; CI runs it as its own
# job, so nothing about the audio pipeline merges unmeasured.
audio-test:
	$(call require-audiogen)
	cd "$(AUDIOGEN)" && "$(abspath $(AUDIOGEN_PY))" -m unittest discover tests

# The sprite generator's own merge bar: cell geometry, ramps, phase sheets, the
# animation manifest, the palette mirrored off the game's own code, and two
# full runs of the pipeline in two processes byte for byte. Out of
# `make verify` because it needs a Python venv a clone of this repo does not
# have, and because it costs ~300 s — mostly the terrain and paint contract
# suites, which render sheets to read them back. CI runs it as its own job.
sprites-test:
	$(call require-spritegen)
	cd "$(SPRITEGEN)" && "$(abspath $(SPRITEGEN_PY))" -m unittest discover tests

# How much of each terrain tile's grain every zoom rung draws — the cast
# shadow's density study, asked of the ground it falls on. A readout, not a bar:
# out of `make verify` and out of `make sprites-test`, and it fails nothing.
# `docs/terrain_grain.md` is the committed reading.
grain-census:
	$(call require-spritegen)
	cd "$(SPRITEGEN)" && "$(abspath $(SPRITEGEN_PY))" tests/grain_census.py $(GRAIN)

# The portrait generator's own merge bar: the faction palette mirrored off the
# game's own code, and two runs of the pipeline byte for byte. Out of
# `make verify` with the other two, for the venv. CI runs it as its own job.
portraits-test:
	$(call require-portraitgen)
	cd "$(PORTRAITGEN)" && "$(abspath $(PORTRAITGEN_PY))" -m unittest discover tests

audio-lint:
	$(call require-audiogen)
	cd "$(AUDIOGEN)" && "$(abspath $(AUDIOGEN_PY))" -m ruff check . \
		&& "$(abspath $(AUDIOGEN_PY))" -m ruff format --check .

sprites-lint:
	$(call require-spritegen)
	cd "$(SPRITEGEN)" && "$(abspath $(SPRITEGEN_PY))" -m ruff check . \
		&& "$(abspath $(SPRITEGEN_PY))" -m ruff format --check .

portraits-lint:
	$(call require-portraitgen)
	cd "$(PORTRAITGEN)" && "$(abspath $(PORTRAITGEN_PY))" -m ruff check . \
		&& "$(abspath $(PORTRAITGEN_PY))" -m ruff format --check .

# Every generator's Python lint gate, each under its own ruff.toml, and the same
# two commands CI runs. Out of `make verify` with the suites, for the venv.
generators-lint: audio-lint sprites-lint portraits-lint

generators-test: audio-test sprites-test portraits-test

# The snapshot gate: a fresh generation against the art installed under assets/,
# so a regeneration nobody ran `make tiles` for fails here. Compared pixel for
# pixel — a different Pillow encodes the same picture into different bytes.
sprites-snapshot:
	$(call require-spritegen)
	@out=$$(mktemp -d) && \
		"$(SPRITEGEN_PY)" "$(SPRITEGEN)/sprite_generator.py" -o "$$out" && \
		"$(SPRITEGEN_PY)" "$(SPRITEGEN)/tests/check_snapshots.py" "$$out"; \
		status=$$?; rm -rf "$$out"; exit $$status

# The same gate for the sounds: the effects byte for byte, the marches by their
# decoded samples — an Ogg's bytes belong to the libVorbis that encoded them.
audio-snapshot:
	$(call require-audiogen)
	@out=$$(mktemp -d) && \
		"$(AUDIOGEN_PY)" "$(AUDIOGEN)/audio_generator.py" -o "$$out" && \
		"$(AUDIOGEN_PY)" "$(AUDIOGEN)/tests/check_snapshots.py" "$$out"; \
		status=$$?; rm -rf "$$out"; exit $$status

# The same gate for the commander art, in both directions: a generated file with
# no committed twin, and a committed file the generator no longer emits.
portraits-snapshot:
	$(call require-portraitgen)
	@out=$$(mktemp -d) && \
		"$(PORTRAITGEN_PY)" "$(PORTRAITGEN)/portrait_generator.py" -o "$$out" && \
		"$(PORTRAITGEN_PY)" "$(PORTRAITGEN)/tests/check_snapshots.py" "$$out"; \
		status=$$?; rm -rf "$$out"; exit $$status

# Holds every shipped campaign to the bar a playable mission clears. Run it after
# authoring a mission; what it refuses is listed in docs/campaign_authoring.md.
campaigns:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/check_campaigns.gd

# How hard every shipped mission is: each one played to a verdict with both
# armies driven by the planner at the mission's own tier, over N seeds, plus the
# odds and the income the player's side opens on. `make campaigns` says a
# mission is playable; this says how it played. A measurement, not a gate — it
# stays out of `make verify` and `make test`, and it edits no content.
# docs/campaign_difficulty.md is the committed record and the caveats to read
# before acting on a row. Narrow it while iterating on an edit:
#   make campaign-difficulty CAMPAIGN="--campaign=the_long_front --seeds=3"
CAMPAIGN ?=
campaign-difficulty:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_campaign_difficulty.gd -- $(CAMPAIGN)

# Regenerates the art under assets/portraits with generators/portraits and
# re-imports so the new PNGs register: the five faction emblems and the
# twenty-three commander busts, which is the whole of it — nothing else bakes
# this art. Committed art, so this only needs rerunning when the generator
# changes or a commander is added. `make portraits-snapshot` is its gate.
portraits:
	$(call require-portraitgen)
	"$(PORTRAITGEN_PY)" "$(PORTRAITGEN)/portrait_generator.py" \
		-o "$(PORTRAITGEN)/out" --install "$(CURDIR)"
	$(MAKE) import

import:
	$(call require-godot)
	$(GODOT) --headless --path . --import

# Mobile packaging (mobile plan MB1). Imports first the way run and screenshot
# do: an export of an unimported tree packages nothing but the source files.
# Needs a one-off machine setup — 4.7.1 export templates plus the Android SDK,
# JDK and debug keystore paths in the editor settings, none of which belong in
# the repository. README.md "Mobile builds (Android)" is the recipe.
export-android: import
	$(call require-godot)
	@mkdir -p $(dir $(ANDROID_APK))
	$(GODOT) --headless --path . --export-debug "Android" $(CURDIR)/$(ANDROID_APK)
	@ls -l $(ANDROID_APK)

# iOS packaging (mobile plan MB9). The preset exports an Xcode project rather
# than an .ipa, so this target needs no signing identity: what it leaves in
# build/ios is grid_commanders.xcodeproj, which Xcode builds, runs and archives.
# IOS_TEAM_ID is optional and is written into that GENERATED project, never into
# export_presets.cfg — a tracked file stays out of the build path. README.md
# "Mobile builds (iOS)" is the recipe and the simulator command line.
export-ios: import
	$(call require-godot)
	@mkdir -p $(dir $(IOS_XCODEPROJ))
	$(GODOT) --headless --path . --export-debug "iOS" $(CURDIR)/$(IOS_IPA)
	@test -z "$(IOS_TEAM_ID)" || { \
		sed -i '' 's/$(IOS_TEAM_PLACEHOLDER)/$(IOS_TEAM_ID)/g' \
			$(IOS_XCODEPROJ)/project.pbxproj $(IOS_EXPORT_OPTIONS); \
		echo "export-ios: development team set to $(IOS_TEAM_ID)"; }
	@ls -d $(IOS_XCODEPROJ)

# The battle scene is launched directly so demos and captures skip the menu.
screenshot: import
	$(GODOT_GUI) --path . $(BATTLE) -- --screenshot=$(CURDIR)/screenshot.png

menu-screenshot: import
	$(GODOT_GUI) --path . -- --screenshot=$(CURDIR)/screenshot.png

# The G1 gate: renders a card for all twenty-three commander records at once, so a
# missing portrait or empty copy field shows up as a crash or a blank card.
gallery-screenshot: import
	$(GODOT_GUI) --path . scenes/menu/commander_gallery.tscn -- --screenshot=$(CURDIR)/screenshot.png

# The mobile soak's desktop baseline (mobile plan MB8): how long a computer turn
# takes to plan on the busiest board, and what the replay recorder's per-command
# flush costs. A measurement, not a gate — out of `make verify` and `make test`,
# and it tunes nothing. docs/mobile_soak.md is the committed record; the device
# half of MB8 is played by hand and written down there too. Examples:
#   make mobile-soak SOAK="--seeds=4 --days=30"
#   make mobile-soak SOAK="--map=meridian --grouping=1v2 --tier=normal"
SOAK ?=
mobile-soak:
	$(call require-godot)
	$(GODOT) --headless --path . -s res://tools/run_mobile_soak.gd -- $(SOAK)

.PHONY: run hotseat test verify smoke check determinism lint format format-check tiles \
	atlases ui-art \
	audio audio-test audio-lint audio-snapshot sprites-test sprites-lint \
	sprites-snapshot grain-census generators-lint generators-test \
	portraits-test portraits-lint portraits-snapshot \
	generators-venv portraits import campaign-difficulty export-android export-ios \
	screenshot menu-screenshot gallery-screenshot commander-balance difficulty-check \
	balance-sim balance-pool bulwark-measure board-measure ai-arena arena-report arena-anchors arena-search \
	balance-watch replay replay-report campaigns legibility-check mobile-soak
