class_name BalanceReportHtml
extends RefCounted
## Draws a Balance Lab run: the win-rate table as bars against the standing
## bands, per-board first-seat bias, and the funds / army-value curves the
## timeline promises — the numbers a spreadsheet makes you squint at.
##
## Two rules it is held to (plan BS4):
##
##  1. **It computes nothing.** Every figure is read from summary.json or
##     timeline.csv. The report can therefore be checked against the raw files by
##     hand, and it can never disagree with them.
##  2. **It is self-contained.** One file, inline CSS, inline SVG, no script, no
##     CDN, no server — it opens off disk next to the CSVs it renders, and it is
##     gitignored with the rest of the report.
##
## Node-free, like everything else here.

## How many per-match curves to draw. A full sweep is hundreds of matches and a
## wall of sparklines reads as noise; the count that was dropped is printed on
## the page rather than silently trimmed.
const MAX_CURVES := 12

const STYLE := """
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body {
  margin: 0; padding: 2rem 1.5rem 4rem;
  background: #0f1720; color: #d7e3ee;
  font: 15px/1.6 ui-sans-serif, -apple-system, "Segoe UI", Helvetica, sans-serif;
}
main { max-width: 1080px; margin: 0 auto; }
h1 { font-size: 1.6rem; margin: 0 0 .25rem; letter-spacing: -.01em; }
h2 { font-size: 1.05rem; margin: 2.5rem 0 .75rem; text-transform: uppercase;
     letter-spacing: .1em; color: #7fa7c8; font-weight: 700; }
.sub { color: #8ba3ba; margin: 0 0 1.5rem; }
.cards { display: flex; flex-wrap: wrap; gap: .75rem; }
.card { background: #16212d; border: 1px solid #23313f; border-radius: .5rem;
        padding: .7rem 1rem; min-width: 8.5rem; }
.card b { display: block; font-size: 1.5rem; font-variant-numeric: tabular-nums; }
.card span { color: #8ba3ba; font-size: .8rem; text-transform: uppercase;
             letter-spacing: .06em; }
table { width: 100%; border-collapse: collapse; font-variant-numeric: tabular-nums; }
th { text-align: left; font-size: .75rem; text-transform: uppercase;
     letter-spacing: .07em; color: #7fa7c8; padding: .4rem .5rem;
     border-bottom: 1px solid #2b3a4a; }
td { padding: .45rem .5rem; border-bottom: 1px solid #1b2733; }
td.num { text-align: right; }
tr:hover td { background: #16212d; }
.bar { position: relative; height: 1.1rem; background: #1b2733; border-radius: 2px; }
.bar i { position: absolute; top: 0; bottom: 0; display: block; border-radius: 2px; }
.bar u { position: absolute; top: -2px; bottom: -2px; width: 1px; background: #4a6076; }
.band { position: absolute; top: 0; bottom: 0; background: #1f3324; }
.ok i { background: #5d9f3e; }
.watch i { background: #d58a24; }
.WARN i { background: #d94d3f; }
.mirror i { background: #4a6076; }
.pill { display: inline-block; padding: .05rem .45rem; border-radius: 999px;
        font-size: .72rem; font-weight: 700; letter-spacing: .04em; }
.pill.ok { background: #1f3324; color: #86c95a; }
.pill.watch { background: #35290f; color: #e0a53d; }
.pill.WARN { background: #3a1c18; color: #ef7a6c; }
.pill.mirror { background: #22303f; color: #9fb6cb; }
.pill.low { background: #35290f; color: #e0a53d; }
.pill.naval { background: #15293d; color: #6fa8dc; }
.notes { padding-left: 1.1rem; }
.notes li { margin: .4rem 0; color: #c2d3e2; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1rem; }
figure { margin: 0; background: #16212d; border: 1px solid #23313f;
         border-radius: .5rem; padding: .75rem; overflow: hidden; }
figcaption { font: 600 .72rem/1.4 ui-monospace, Menlo, monospace; color: #8ba3ba;
             margin-bottom: .4rem; overflow-wrap: anywhere; }
svg { display: block; width: 100%; height: auto; }
.legend { font-size: .72rem; color: #8ba3ba; margin-top: .3rem; }
.legend b { font-weight: 700; }
.red { color: #ef7a6c; }
.blue { color: #6fa8dc; }
.wrap { overflow-x: auto; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #23313f;
         color: #7089a0; font-size: .8rem; }
"""


static func render(summary: Dictionary, timeline: Array[Dictionary]) -> String:
	var run: Dictionary = summary["run"]
	var out: Array[String] = []
	out.append('<!doctype html><html lang="en"><head><meta charset="utf-8">')
	out.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
	out.append("<title>Balance Lab — %s</title>" % _esc(run["label"]))
	out.append("<style>%s</style></head><body><main>" % STYLE)
	out.append("<h1>Balance Lab</h1>")
	out.append(
		(
			'<p class="sub">%s · %d seeds · day cap %d · both seats played</p>'
			% [_esc(run["label"]), int(run["seeds"]), int(run["days_cap"])]
		)
	)
	out.append(_totals(summary))
	out.append(_notes(summary))
	out.append(_values(summary))
	out.append(_bias(summary))
	out.append(_curves(timeline))
	out.append(
		(
			"<footer>Generated by tools/run_balance_sim.gd from this run's own"
			+ " matches.csv, timeline.csv and summary.json — every number above is"
			+ " read from those files, none is computed here. See"
			+ " docs/balance_sim.md.</footer>"
		)
	)
	out.append("</main></body></html>")
	return "\n".join(out)


# --- sections ----------------------------------------------------------------


static func _totals(summary: Dictionary) -> String:
	var totals: Dictionary = summary["totals"]
	var bias: Dictionary = summary["bias"]["overall"]
	var cards: Array[String] = []
	cards.append(_card(str(totals["matches"]), "matches"))
	cards.append(_card(str(totals["decisive"]), "decisive"))
	cards.append(_card(str(totals["draws"]), "draws"))
	cards.append(_card("%+.1f pp" % bias["bias_pp"], "first-seat bias"))
	cards.append(
		_card(
			"clean" if totals["invariants_clean"] else "FAIL",
			"%d rejected · %d stalls" % [totals["total_rejected"], totals["total_cap_stalls"]]
		)
	)
	return '<div class="cards">%s</div>' % "".join(cards)


static func _card(value: String, label: String) -> String:
	return '<div class="card"><b>%s</b><span>%s</span></div>' % [_esc(value), _esc(label)]


static func _notes(summary: Dictionary) -> String:
	var notes: Array = summary["notes"]
	if notes.is_empty():
		return ""
	var items: Array[String] = []
	for note: String in notes:
		items.append("<li>%s</li>" % _esc(note))
	return '<h2>How to read this run</h2><ul class="notes">%s</ul>' % "".join(items)


## The win-rate table. Each bar is drawn against the preferred band shaded behind
## it and a 50%% tick, so "is this in band?" is answered by looking rather than by
## comparing two numbers.
static func _values(summary: Dictionary) -> String:
	var bands: Dictionary = summary["bands"]
	var preferred: Array = bands["preferred"]
	var rows: Array[String] = []
	for entry: Dictionary in summary["values"]:
		var economy: Dictionary = entry["economy"]
		var term: Dictionary = entry["termination"]
		var tags: Array[String] = [_pill(entry["flag"], entry["flag"])]
		if entry["confidence"] == "low":
			tags.append(_pill("low", "low confidence"))
		if entry["naval_bounded"]:
			tags.append(_pill("naval", "AI-bounded"))
		(
			rows
			. append(
				(
					(
						'<tr><td>%s</td><td class="num">%.1f%%</td><td>%s</td>'
						+ '<td class="num">%d</td><td class="num">%.0f%%</td>'
						+ '<td class="num">%.0f</td><td class="num">%s</td><td>%s</td></tr>'
					)
					% [
						_esc(entry["value"]),
						entry["win_rate"],
						_bar(entry["win_rate"], entry["flag"], preferred[0], preferred[1]),
						int(entry["matches"]),
						entry["resolved_pct"],
						economy["killed_per_1000_spent"],
						ratio(economy["exchange_ratio"]),
						"".join(tags),
					]
				)
			)
		)
		rows.append(
			(
				(
					'<tr><td colspan="8" style="color:#7089a0;font-size:.78rem;'
					+ 'border-bottom:1px solid #1b2733;padding-top:0">'
					+ "endings — rout %d · hq %d · day cap %d · command cap %d"
					+ " &nbsp;·&nbsp; mean day %.1f</td></tr>"
				)
				% [
					term["rout"],
					term["hq"],
					term["day_cap"],
					term["command_cap"],
					entry["mean_day_ended"]
				]
			)
		)
	return (
		(
			"<h2>Win rate, side-normalized</h2>"
			+ '<div class="wrap"><table><thead><tr><th>value</th><th class="num">win</th>'
			+ '<th style="width:34%%">band %.0f–%.0f%% preferred</th><th class="num">n</th>'
			+ '<th class="num">resolved</th><th class="num">kills/1k</th>'
			+ '<th class="num">exch.</th><th>flags</th></tr></thead><tbody>%s</tbody></table></div>'
		)
		% [preferred[0], preferred[1], "".join(rows)]
	)


static func _bar(rate: float, flag: String, band_low: float, band_high: float) -> String:
	return (
		(
			'<div class="bar %s"><span class="band" style="left:%.1f%%;width:%.1f%%"></span>'
			+ '<i style="left:0;width:%.1f%%"></i><u style="left:50%%"></u></div>'
		)
		% [flag, band_low, band_high - band_low, clampf(rate, 0.0, 100.0)]
	)


## Per-board first-seat bias, drawn from the centre so the direction reads at a
## glance: right of the tick is the first seat winning, left is the second.
static func _bias(summary: Dictionary) -> String:
	var per_map: Array = summary["bias"]["per_map"]
	if per_map.size() < 2:
		return ""
	var threshold: float = summary["bands"]["max_side_bias_pp"]
	var rows: Array[String] = []
	for entry: Dictionary in per_map:
		var bias: float = entry["bias_pp"]
		# Bias runs -100..+100 pp across a bar 100 units wide centred on 50, so
		# half the magnitude is the distance from the tick. Positive grows right
		# (the first seat winning), negative grows left.
		var half := clampf(absf(bias) / 2.0, 0.0, 50.0)
		var left := 50.0 if bias >= 0.0 else 50.0 - half
		var flag := "ok" if entry["ok"] else "WARN"
		(
			rows
			. append(
				(
					(
						'<tr><td>%s%s</td><td class="num">%+.1f pp</td>'
						+ '<td><div class="bar %s"><i style="left:%.1f%%;width:%.1f%%"></i>'
						+ '<u style="left:50%%"></u></div></td>'
						+ '<td class="num">%d</td><td>%s</td></tr>'
					)
					% [
						_esc(entry["map"]),
						' <span class="pill naval">naval</span>' if entry["naval_bounded"] else "",
						bias,
						flag,
						left,
						half,
						int(entry["decisive"]),
						_pill(flag, flag),
					]
				)
			)
		)
	# The count column is headed "decisive" because that is what the cell holds:
	# this table's denominator is every game with a winner, day-cap ones included.
	# "Resolved" is the stricter word — endings that happened on the board — and it
	# belongs to the win-rate table above, which has a column of its own for it.
	return (
		(
			"<h2>First-seat bias per board</h2>"
			+ '<div class="wrap"><table><thead><tr><th>board</th><th class="num">bias</th>'
			+ '<th style="width:40%%">second seat &nbsp;&larr;&nbsp;|&nbsp;&rarr;&nbsp; first seat'
			+ ' (threshold ±%.0f pp)</th><th class="num">decisive</th><th></th>'
			+ "</tr></thead><tbody>%s</tbody></table></div>"
		)
		% [threshold, "".join(rows)]
	)


## The timeline, drawn. One small multiple per match: both sides' army value
## (solid) and treasury (dotted) over the days the match lasted — the shape that
## answers "what actually happened here?" without opening a spreadsheet.
static func _curves(timeline: Array[Dictionary]) -> String:
	var order: Array[String] = []
	var by_match: Dictionary = {}
	for row in timeline:
		var id: String = row["match_id"]
		if not by_match.has(id):
			by_match[id] = []
			order.append(id)
		by_match[id].append(row)
	if order.is_empty():
		return ""
	var shown := mini(order.size(), MAX_CURVES)
	var figures: Array[String] = []
	for i in shown:
		figures.append(_curve(order[i], by_match[order[i]]))
	var dropped := ""
	if order.size() > shown:
		dropped = (
			" Showing the first %d of %d matches — the rest are in timeline.csv."
			% [shown, order.size()]
		)
	return (
		(
			"<h2>Per-match timeline</h2>"
			+ '<p class="sub"><b class="red">Red</b> and <b class="blue">Blue</b> army value'
			+ " (solid) and treasury (dotted), by day.%s</p>"
			+ '<div class="grid">%s</div>'
		)
		% [dropped, "".join(figures)]
	)


static func _curve(match_id: String, rows: Array) -> String:
	# The armies are whoever the timeline says played, in the order it first
	# mentions them, rather than the two the Lab's side specs happen to name — a
	# figure that quietly drops a side is worse than no figure.
	var series: Dictionary = {}
	var top := 1.0
	for row: Dictionary in rows:
		var team := int(row["team"])
		if not series.has(team):
			series[team] = {"army": [], "funds": []}
		var day := int(row["day"])
		var army := float(row["army_value"])
		var funds := float(row["funds_end"])
		series[team]["army"].append(Vector2(day, army))
		series[team]["funds"].append(Vector2(day, funds))
		top = maxf(top, maxf(army, funds))
	var days := 1.0
	for team: int in series:
		for point: Vector2 in series[team]["army"]:
			days = maxf(days, point.x)
	var paths: Array[String] = []
	for team: int in series:
		var colour := _team_colour(team)
		paths.append(_polyline(series[team]["army"], days, top, colour, ""))
		paths.append(_polyline(series[team]["funds"], days, top, colour, "2 3"))
	return (
		(
			"<figure><figcaption>%s</figcaption>"
			+ '<svg viewBox="0 0 300 110" preserveAspectRatio="none" role="img">'
			+ '<line x1="0" y1="100" x2="300" y2="100" stroke="#2b3a4a" stroke-width="1"/>'
			+ "%s</svg>"
			+ '<div class="legend">peak %s · %d days</div></figure>'
		)
		% [_esc(match_id), "".join(paths), _thousands(int(top)), int(days)]
	)


## The line an army is drawn in. Seats 1 and 2 keep the red and blue the legend
## and the rest of the page name them in; a third or fourth army — which no Lab
## run seats today, since a side spec is red or blue — gets a line of its own
## rather than borrowing one.
static func _team_colour(team: int) -> String:
	match team:
		1:
			return "#ef7a6c"
		2:
			return "#6fa8dc"
		3:
			return "#c9a227"
	return "#7bc47f"


## A day/value series as SVG. The viewBox is 300x110 with the baseline at y=100,
## so every small multiple shares one geometry and they can be read side by side.
static func _polyline(
	points: Array, days: float, top: float, colour: String, dash: String
) -> String:
	if points.size() < 2:
		return ""
	var parts: Array[String] = []
	for point: Vector2 in points:
		var x := 300.0 * (point.x - 1.0) / maxf(1.0, days - 1.0)
		var y := 100.0 - 90.0 * point.y / top
		parts.append("%.1f,%.1f" % [x, y])
	var dash_attr := ' stroke-dasharray="%s"' % dash if dash != "" else ""
	return (
		'<polyline fill="none" stroke="%s" stroke-width="1.5" points="%s"%s/>'
		% [colour, " ".join(parts), dash_attr]
	)


# --- helpers -----------------------------------------------------------------


## An exchange ratio, or an em dash when it has no denominator — a side that lost
## nothing at all has an undefined ratio, and printing a huge number for it would
## read as a measurement instead of a missing divisor. Public so the console
## summary prints it the same way.
static func ratio(value: float) -> String:
	return "—" if value < 0.0 else "%.2f" % value


static func _pill(kind: String, label: String) -> String:
	return '<span class="pill %s">%s</span>' % [kind, _esc(label)]


static func _thousands(value: int) -> String:
	var text := str(absi(value))
	var out := ""
	var count := 0
	for i in range(text.length() - 1, -1, -1):
		out = text[i] + out
		count += 1
		if count % 3 == 0 and i > 0:
			out = " " + out
	return ("-" if value < 0 else "") + out


static func _esc(value: Variant) -> String:
	return str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace(
		'"', "&quot;"
	)
