extends RefCounted
## The per-commander face specs tools/commander_face_svg.gd draws from, split
## out of it so the drawer has room to draw. Data only — no colours, no
## geometry, nothing that knows what an SVG is.
##
## Not a class_name: this is offline art tooling, reached by preload, and the
## game never sees it.

## Per-commander spec, straight from the handoff's FACES table, with the skull
## the collar and the nose this repo gave each general on top of it. `head` is
## [width, jaw, crown, spread] (see HEAD_DEFAULT), `pose` is
## [tilt degrees, zoom, mirrored], `nose` is one of the three glyphs (see
## NOSE_TICK), `collar` is one of the three cuts above, and `pip` puts a rank
## stud on it — the four costliest powers only. Heads are cast against doctrine:
## the immovable are wide and square, the quick and the clever narrow and
## tapered, and the three grey veterans wear a low crown. Collars are cast the
## same way: line officers wear the V, staff and planners the mandarin band, the
## veterans and the admiral double-breasted. So are the expressions — `brow`,
## `eyes`, `mouth` and the `eye` size each general's power quote is read off, so
## a face looks like it could say its own line.
const FACES := {
	&"alina_ward":
	{
		"skin": &"light",
		"hair": &"auburn",
		"style": &"long",
		"brow": &"soft",
		"eyes": &"f",
		"mouth": &"smile",
		"eye": 1.02,
		"facial": &"none",
		"acc": &"none",
		"earring": true,
		"collar": &"v",
		"head": [0.96, &"round", 0.5, 1.0],
		"nose": &"tick",
		"pose": [-5.0, 1.2, false],
		"bg": &"rays",
		"prop": &"sabre",
	},
	&"gideon_holt":
	{
		"skin": &"medium",
		"hair": &"grey",
		"style": &"short",
		"brow": &"heavy",
		"eyes": &"m",
		"mouth": &"smile",
		"eye": 0.91,
		"facial": &"beard",
		"acc": &"glasses",
		"collar": &"double",
		"head": [1.08, &"square", -2.0, 1.0],
		"nose": &"broad",
		"pose": [3.0, 1.14, false],
		"bg": &"halftone",
		"prop": &"pipe",
	},
	&"rhea_sol":
	{
		"skin": &"tan",
		"hair": &"black",
		"style": &"ponytail",
		"brow": &"angled",
		"eyes": &"narrow",
		"mouth": &"grin",
		"eye": 0.98,
		"facial": &"none",
		"acc": &"goggles",
		"collar": &"mandarin",
		"head": [0.92, &"tapered", 0.0, 1.05],
		"nose": &"tick",
		"pose": [-8.0, 1.24, true],
		"bg": &"speed",
		"prop": &"wrench",
	},
	&"cass_orlov":
	{
		"skin": &"light",
		"hair": &"brown",
		"style": &"buzz",
		"brow": &"cocked",
		"eyes": &"m",
		"mouth": &"smirk",
		"eye": 0.9,
		"facial": &"stubble",
		"acc": &"scar",
		"collar": &"v",
		"head": [1.1, &"square", 0.5, 0.96],
		"nose": &"hook",
		"pose": [6.0, 1.22, false],
		"bg": &"wedge",
		"prop": &"cigar",
	},
	&"mara_voss":
	{
		"skin": &"medium",
		"hair": &"black",
		"style": &"bun",
		"brow": &"angled",
		"eyes": &"f",
		"mouth": &"stern",
		"eye": 0.95,
		"facial": &"none",
		"acc": &"none",
		"collar": &"v",
		"head": [0.94, &"tapered", 1.0, 1.0],
		"nose": &"hook",
		"pose": [0.0, 1.18, false],
		"bg": &"bars",
		"prop": &"baton",
	},
	&"viktor_draeg":
	{
		"skin": &"light",
		"hair": &"grey",
		"style": &"bald",
		"brow": &"heavy",
		"eyes": &"wide",
		"mouth": &"open",
		"eye": 1.06,
		"facial": &"mustache",
		"acc": &"eyepatch",
		"collar": &"v",
		"head": [1.12, &"square", -1.0, 0.94],
		"nose": &"broad",
		"pose": [-3.0, 1.26, false],
		"bg": &"burst",
		"prop": &"medal",
	},
	&"cassian_rook":
	{
		"skin": &"light",
		"hair": &"blonde",
		"style": &"sidepart",
		"brow": &"cocked",
		"eyes": &"narrow",
		"mouth": &"wry",
		"eye": 0.92,
		"facial": &"none",
		"acc": &"none",
		"collar": &"mandarin",
		"head": [0.92, &"tapered", 1.0, 1.0],
		"nose": &"hook",
		"pose": [8.0, 1.18, true],
		"bg": &"halftone",
		"prop": &"card",
	},
	&"lyra_quill":
	{
		"skin": &"pale",
		"hair": &"platinum",
		"style": &"bob",
		"brow": &"soft",
		"eyes": &"closed",
		"mouth": &"wry",
		"eye": 0.86,
		"facial": &"none",
		"acc": &"glasses",
		"collar": &"mandarin",
		"head": [0.88, &"tapered", 2.0, 0.94],
		"nose": &"hook",
		"pose": [-4.0, 1.12, false],
		"bg": &"grid",
		"prop": &"book",
	},
	&"orin_flux":
	{
		"skin": &"medium",
		"hair": &"black",
		"style": &"spiky",
		"brow": &"angled",
		"eyes": &"wide",
		"mouth": &"laugh",
		"eye": 1.04,
		"facial": &"none",
		"acc": &"headset",
		"collar": &"mandarin",
		"head": [0.9, &"round", 1.0, 1.08],
		"nose": &"tick",
		"pose": [-9.0, 1.22, false],
		"bg": &"speed",
		"prop": &"drone",
	},
	&"nia_rowan":
	{
		"skin": &"tan",
		"hair": &"brown",
		"style": &"braid",
		"brow": &"soft",
		"eyes": &"f",
		"mouth": &"wry",
		"eye": 1.0,
		"facial": &"none",
		"acc": &"headband",
		"freckles": true,
		"collar": &"v",
		"head": [0.92, &"round", 0.5, 1.06],
		"nose": &"broad",
		"pose": [4.0, 1.16, false],
		"bg": &"rays",
		"prop": &"falcon",
	},
	&"sable_wren":
	{
		"skin": &"pale",
		"hair": &"black",
		"style": &"hood",
		"brow": &"soft",
		"eyes": &"lidded",
		"mouth": &"neutral",
		"eye": 0.9,
		"facial": &"none",
		"acc": &"hood",
		"collar": &"v",
		"head": [0.88, &"tapered", 0.5, 0.96],
		"nose": &"tick",
		"pose": [0.0, 1.24, false],
		"bg": &"wedge",
		"prop": &"dagger",
	},
	&"tomas_reed":
	{
		"skin": &"dark",
		"hair": &"black",
		"style": &"curly",
		"brow": &"raised",
		"eyes": &"m",
		"mouth": &"grin",
		"eye": 1.03,
		"facial": &"stubble",
		"acc": &"bandana",
		"collar": &"v",
		"head": [1.06, &"round", 0.0, 1.0],
		"nose": &"broad",
		"pose": [-6.0, 1.2, false],
		"bg": &"burst",
		"prop": &"radio",
	},
	&"ines_calder":
	{
		"skin": &"dark",
		"hair": &"black",
		"style": &"bun",
		"brow": &"cocked",
		"eyes": &"f",
		"mouth": &"smirk",
		"eye": 0.93,
		"facial": &"none",
		"acc": &"glasses",
		"collar": &"mandarin",
		"head": [0.94, &"round", 0.5, 1.02],
		"nose": &"tick",
		"pose": [-4.0, 1.18, false],
		"bg": &"grid",
		"prop": &"ledger",
	},
	&"konrad_vale":
	{
		"skin": &"pale",
		"hair": &"platinum",
		"style": &"sidepart",
		"brow": &"angled",
		"eyes": &"narrow",
		"mouth": &"stern",
		"eye": 0.87,
		"facial": &"mustache",
		"acc": &"none",
		"collar": &"double",
		"head": [1.04, &"tapered", -2.0, 0.98],
		"nose": &"hook",
		"pose": [5.0, 1.25, false],
		"bg": &"wedge",
		"prop": &"helm",
	},
	&"perrin_ash":
	{
		"skin": &"tan",
		"hair": &"auburn",
		"style": &"short",
		"brow": &"raised",
		"eyes": &"m",
		"mouth": &"grin",
		"eye": 1.01,
		"facial": &"none",
		"acc": &"goggles",
		"collar": &"v",
		"head": [0.98, &"round", 0.0, 1.06],
		"nose": &"hook",
		"pose": [-7.0, 1.2, true],
		"bg": &"speed",
		"prop": &"plane",
	},
	&"halden_marr":
	{
		"skin": &"medium",
		"hair": &"grey",
		"style": &"curly",
		"brow": &"heavy",
		"eyes": &"m",
		"mouth": &"neutral",
		"eye": 0.97,
		"facial": &"beard",
		"acc": &"none",
		"collar": &"double",
		"head": [1.08, &"round", -2.0, 1.0],
		"nose": &"hook",
		"pose": [3.0, 1.16, false],
		"bg": &"rays",
		"prop": &"anchor",
	},
	&"dane_ferrow":
	{
		"skin": &"dark",
		"hair": &"black",
		"style": &"buzz",
		"brow": &"heavy",
		"eyes": &"narrow",
		"mouth": &"clench",
		"eye": 0.94,
		"facial": &"stubble",
		"acc": &"scar",
		"collar": &"mandarin",
		"head": [1.08, &"square", 0.0, 0.96],
		"nose": &"broad",
		"pose": [7.0, 1.24, false],
		"bg": &"burst",
		"prop": &"coins",
	},
	&"iris_colt":
	{
		"skin": &"light",
		"hair": &"blonde",
		"style": &"ponytail",
		"brow": &"raised",
		"eyes": &"f",
		"mouth": &"smile",
		"eye": 1.05,
		"facial": &"none",
		"acc": &"headset",
		"collar": &"v",
		"pip": true,
		"head": [0.9, &"tapered", 0.5, 1.08],
		"nose": &"tick",
		"pose": [-6.0, 1.22, false],
		"bg": &"halftone",
		"prop": &"whistle",
	},
	&"sera_lark":
	{
		"skin": &"dark",
		"hair": &"darkbrown",
		"style": &"ponytail",
		"brow": &"raised",
		"eyes": &"f",
		"mouth": &"laugh",
		"eye": 0.99,
		"facial": &"none",
		"acc": &"bandana",
		"collar": &"mandarin",
		"head": [0.9, &"round", 1.0, 1.04],
		"nose": &"tick",
		"pose": [5.0, 1.2, true],
		"bg": &"wedge",
		"prop": &"compass",
	},
	&"iona_vance":
	{
		"skin": &"tan",
		"hair": &"brown",
		"style": &"bob",
		"brow": &"soft",
		"eyes": &"f",
		"mouth": &"stern",
		"eye": 0.96,
		"facial": &"none",
		"acc": &"none",
		"collar": &"mandarin",
		"pip": true,
		"head": [1.0, &"square", 0.0, 0.98],
		"nose": &"tick",
		"pose": [0.0, 1.16, false],
		"bg": &"grid",
		"prop": &"scales",
	},
	&"ivar_thorne":
	{
		"skin": &"light",
		"hair": &"darkbrown",
		"style": &"long",
		"brow": &"angled",
		"eyes": &"narrow",
		"mouth": &"snarl",
		"eye": 0.85,
		"facial": &"beard",
		"acc": &"scar",
		"collar": &"v",
		"pip": true,
		"head": [1.1, &"square", -0.5, 0.96],
		"nose": &"broad",
		"pose": [-5.0, 1.26, true],
		"bg": &"burst",
		"prop": &"axe",
	},
	&"radek_morn":
	{
		"skin": &"medium",
		"hair": &"darkbrown",
		"style": &"bald",
		"brow": &"heavy",
		"eyes": &"lidded",
		"mouth": &"clench",
		"eye": 0.88,
		"facial": &"beard",
		"acc": &"none",
		"collar": &"double",
		"pip": true,
		"head": [1.14, &"square", -1.5, 0.94],
		"nose": &"hook",
		"pose": [2.0, 1.28, false],
		"bg": &"halftone",
		"prop": &"hammer",
	},
}
