extends SceneTree
## Generates the game's UI chrome art: the range overlay, the grid cursor
## sprite, and the project icon.
##
## The terrain and unit atlases are deliberately NOT drawn here any more:
## both are generated by `generators/sprites` and installed by
## `make tiles` (`sprite_generator.py --install`), which is the single source
## of truth for every board sprite. This script owns only the art that has no
## home there — the translucent overlay the scene modulates, the cursor, and
## the icon.

const TILE := 16

const GRASS := Color("78c850")
const ROAD := Color("c9b884")
# The two classic team hues, sampled by the project icon.
const TEAM_RED := Color("d84a3c")
const TEAM_BLUE := Color("3c64d8")

var img: Image


func _init() -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://assets/tiles"))
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://assets/ui"))
	_generate_overlay()
	_generate_cursor()
	_generate_icon()
	print("generate_tiles: wrote overlay.png, cursor.png, icon.png")
	quit()


## Semi-transparent white tile; the scene modulates it (blue = move range).
func _generate_overlay() -> void:
	img = Image.create_empty(TILE, TILE, false, Image.FORMAT_RGBA8)
	img.fill_rect(Rect2i(0, 0, TILE, TILE), Color(1, 1, 1, 0.5))
	img.fill_rect(Rect2i(1, 1, TILE - 2, TILE - 2), Color(1, 1, 1, 0.34))
	img.save_png("res://assets/tiles/overlay.png")


func _generate_cursor() -> void:
	img = Image.create_empty(TILE, TILE, false, Image.FORMAT_RGBA8)
	var shadow := Color(0.05, 0.05, 0.05, 0.9)
	# corner brackets: shadow offset (1,1), then white on top
	for offset: Vector2i in [Vector2i(1, 1), Vector2i.ZERO]:
		var c := Color.WHITE if offset == Vector2i.ZERO else shadow
		for corner: Array in [
			[0, 0, 1, 1],
			[TILE - 6, 0, -1, 1],
			[0, TILE - 6, 1, -1],
			[TILE - 6, TILE - 6, -1, -1],
		]:
			var x: int = corner[0]
			var y: int = corner[1]
			var hx := x if corner[2] > 0 else x
			var hy := y if corner[3] > 0 else y + 4
			var vx := x if corner[2] > 0 else x + 4
			var vy := y if corner[3] > 0 else y
			_safe_fill(hx + offset.x, hy + offset.y, 6, 2, c)
			_safe_fill(vx + offset.x, vy + offset.y, 2, 6, c)
	img.save_png("res://assets/ui/cursor.png")


func _safe_fill(x: int, y: int, w: int, h: int, c: Color) -> void:
	var rect := Rect2i(x, y, w, h).intersection(Rect2i(0, 0, img.get_width(), img.get_height()))
	if rect.has_area():
		img.fill_rect(rect, c)


func _generate_icon() -> void:
	img = Image.create_empty(128, 128, false, Image.FORMAT_RGBA8)
	img.fill(GRASS)
	img.fill_rect(Rect2i(56, 0, 16, 128), ROAD)
	img.fill_rect(Rect2i(0, 56, 128, 16), ROAD)
	img.fill_rect(Rect2i(14, 14, 28, 28), TEAM_RED)
	img.fill_rect(Rect2i(86, 86, 28, 28), TEAM_BLUE)
	img.save_png("res://assets/icon.png")
